# Create a webste with Rust builds for Windows and Linux.
name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo files
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: book-bins-${{ runner.os }}-${{ github.sha }}
          restore-keys: book-bins-${{ runner.os }}-

      - name: Install x11 libraries
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libx11-dev

      - name: Build the binary
        run: cargo build --verbose --profile release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.os }}
          path: target/release/

  build-docs:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bin-*
          merge-multiple: true

      - name: Create the index page
        run: |
          mkdir docs
          echo "<h1>Binary builds</h1>" > docs/index.html
          echo "<ul>" >> docs/index.html
          for file in target/release/*; do
            mv $file docs/
            echo "<li><a href=\"${file}\">${file}</a></li>" >> docs/index.html
          done
          echo "</ul>" >> docs/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    name: Deploy to GitHub Pages
    needs: build-docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
